version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - app_net

  cachebridge-api:
    build:
      context: ./CacheBridgeAPI
    container_name: cachebridge-api
    restart: unless-stopped
    environment:
      PORT: ${API_PORT}
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    depends_on:
      - mongodb
      - redis
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - app_net

  cachebridge-console:
    build:
      context: ./CacheBridgeConsole
    container_name: cachebridge-console
    restart: unless-stopped
    environment:
      PORT: ${CONSOLE_PORT}
      API_URL: http://cachebridge-api:${API_PORT}
    depends_on:
      - cachebridge-api
    ports:
      - "${CONSOLE_PORT}:${CONSOLE_PORT}"
    networks:
      - app_net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - app_net

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - app_net

volumes:
  mongo_data:

networks:
  app_net:
